using System.Globalization;

namespace NovelBook.Services
{
    /// <summary>
    /// Servicio para manejar la localización y traducciones de la aplicación
    /// </summary>
    public static class LocalizationService
    {
        // Diccionario de traducciones
        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
        {
            // Español
            ["es"] = new Dictionary<string, string>
            {
                // LoginPage
                ["Welcome"] = "Bienvenido a NovelBook",
                ["WelcomeSubtitle"] = "Tu biblioteca de novelas ligeras",
                ["Email"] = "Correo electrónico",
                ["Password"] = "Contraseña",
                ["Login"] = "Entrar",
                ["Register"] = "Regístrate",
                ["Guest"] = "Invitado",
                ["ForgotPassword"] = "¿Olvidaste tu contraseña?",
                ["LoginWithSocial"] = "Iniciar sesión con:",
                ["NoAccount"] = "¿No tienes cuenta?",
                ["LoggingIn"] = "Iniciando sesión...",
                ["BiometricLoginButton"] = "🔐 Iniciar con Face ID/Touch ID",

                // RegisterPage
                ["RegisterTitle"] = "Registro",
                ["YourLightNovelWorld"] = "Tu mundo de novelas ligeras",
                ["FillAllFieldsLabel"] = "Llena todos los campos:",
                ["Name"] = "Nombre",
                ["ConfirmPassword"] = "Confirmar contraseña",
                ["PasswordsDoNotMatch"] = "Las contraseñas no coinciden",
                ["PasswordRequirement"] = "La contraseña debe tener al menos 6 caracteres",
                ["CreateAccount"] = "Crear",
                ["CreatingAccount"] = "Creando cuenta...",
                ["AlreadyHaveAccount"] = "¿Ya tienes cuenta?",
                ["LoginHere"] = "Inicia sesión",
                ["FillAllFieldsError"] = "Por favor completa todos los campos",
                ["InvalidEmailError"] = "Por favor ingresa un email válido",
                ["PasswordTooShortError"] = "La contraseña debe tener al menos 6 caracteres",
                ["PasswordsDontMatchError"] = "Las contraseñas no coinciden",
                ["Success"] = "Éxito",
                ["AccountCreatedSuccess"] = "Cuenta creada exitosamente",
                ["ConnectionError"] = "Error de conexión. Verifica tu conexión a internet.",

                // LibraryPage
                ["MyLibrary"] = "Mi Biblioteca",
                ["Reading"] = "Leyendo",
                ["Completed"] = "Completadas",
                ["Favorites"] = "Favoritas",
                ["NoNovels"] = "No hay novelas en tu biblioteca",
                ["SearchLibrary"] = "Buscar en biblioteca...",
                ["Read"] = " leído",
                ["Caps"] = " caps",
                ["All"] = "Todos",
                ["Dropped"] = "Pausadas",
                ["PlanToRead"] = "Planeando leer",
                ["LoginToSeeLibrary"] = "Inicia sesión para ver tu biblioteca",
                ["OptionsFor"] = "Opciones para:",
                ["Cancel"] = "Cancelar",
                ["RemoveFromFavorites"] = "Quitar de favoritos",
                ["AddToFavorites"] = "Agregar a favoritos",
                ["ChangeStatus"] = "Cambiar estado",
                ["StatusUpdated"] = "Estado actualizado",
                ["ErrorPerformingAction"] = "No se pudo realizar la acción",
                ["NewStatus"] = "Nuevo estado",
                ["ChangeStatusTo"] = "Cambiar estado de lectura",
                ["ConfirmAction"] = "¿Estás seguro?",
                ["MarkedAsFavorite"] = "Marcado como favorito",
                ["RemovedFromFavorites"] = "Eliminado de favoritos",

                // ExplorePage
                ["ExploreNovels"] = "Explorar Novelas",
                ["PopularGenres"] = "Géneros Populares",
                ["AllNovels"] = "Todas las Novelas",
                ["FilterByGenre"] = "Filtrar por género",
                ["FilterByStatus"] = "Filtrar por estado",
                ["InProgress"] = "En progreso",
                ["SearchNovels"] = "Buscar novelas...",

                // HistoryPage
                ["History"] = "Historial",
                ["TotalTime"] = "Tiempo total",
                ["ReadingStreak"] = "Racha",
                ["Days"] = "Días",
                ["CompleteHistory"] = "📅 Historial completo",
                ["ByNovel"] = "📚 Por novela",
                ["Today"] = "📆 Hoy",
                ["ThisWeek"] = "📅 Esta semana",
                ["ThisMonth"] = "📅 Este mes",
                ["NoHistoryYet"] = "Aún no has leído ningún capítulo",
                ["LoginToSeeHistory"] = "Inicia sesión para ver tu historial de lectura",
                ["ErrorLoadingHistory"] = "Error al cargar historial: {0}",
                ["ConfirmClearHistory"] = "¿Estás seguro de que quieres borrar todo tu historial de lectura?",
                ["HistoryCleared"] = "Tu historial ha sido borrado",
                ["ErrorClearingHistory"] = "No se pudo borrar el historial",
                ["NoReadingToday"] = "No has leído nada hoy",
                ["NoReadingThisWeek"] = "No has leído nada esta semana",
                ["NoReadingThisMonth"] = "No has leído nada este mes",
                ["Completed2"] = "✓ Completado",
                ["Today"] = "📖 Hoy",
                ["Yesterday"] = "Ayer",
                ["ChaptersRead"] = "📖 {0} caps leídos",
                ["LastRead"] = "📅 Última vez: {0}",

                //NovelDetailPage
                ["Read2"] = "Leer",
                ["Reread"] = "Releer",
                ["Resume"] = "Resumir",
                ["ResumeCap"] = "Resumir Cap.",
                ["ContinueReading"] = "Continuar lectura",
                ["ContinueCap"] = "Continuar Cap.",
                ["ReadCap"] = "Leer Cap.",
                ["AddToLibrary"] = " Agregar",
                ["RemoveFromLibrary"] = " Quitar",
                ["Synopsis"] = "Sinopsis",
                ["Chapters"] = "Capítulos",
                ["Details"] = "Detalles",
                ["Chapter"] = "Capítulo",
                ["AllChapters"] = "Todos",
                ["Unread"] = "Sin leer",
                ["ReverseOrder"] = "↓↑",
                ["SearchChapter"] = "Buscar capítulo...",
                ["NoChaptersYet"] = "Esta novela no tiene capítulos aún",
                ["NoChaptersAvailable"] = "No se encontraron capítulos disponibles",
                ["ChapterNotFound"] = "No se encontró el capítulo solicitado",
                ["Status"] = "Estado:",
                ["Author"] = "Autor:",
                ["Views"] = "Vistas:",
                ["WithoutGenres"] = "Sin géneros asignados",
                ["ConfirmRemoveFromLibrary"] = "¿Eliminar esta novela de tu biblioteca?",
                ["RemovedFromLibrary"] = "Novela eliminada de tu biblioteca",
                ["AddedToLibrary"] = "Novela agregada a tu biblioteca",
                ["ErrorAddingToLibrary"] = "No se pudo agregar a la biblioteca",
                ["ErrorRemovingFromLibrary"] = "No se pudo eliminar de la biblioteca",
                ["ErrorProcessingRequest"] = "Error al procesar la solicitud",
                ["ErrorLoadingDetails"] = "Error al cargar detalles",
                ["ViewReviews"] = "Ver reseñas ({0})",

                // SettingsPage
                ["Settings"] = "Configuración",
                ["Appearance"] = "Apariencia",
                ["AppTheme"] = "Tema de la aplicación",
                ["System"] = "Sistema",
                ["Light"] = "Claro",
                ["Dark"] = "Oscuro",
                ["Language"] = "Idioma",
                ["Spanish"] = "Español",
                ["English"] = "English",
                ["Account"] = "Cuenta",
                ["AccountInfo"] = "Información de cuenta",
                ["BiometricAuth"] = "Autenticación biométrica",
                ["ChangePassword"] = "Cambiar contraseña",
                ["Reading"] = "Lectura",
                ["FontSize"] = "Tamaño de letra",
                ["NightMode"] = "Modo nocturno automático",
                ["KeepScreenOn"] = "Mantener pantalla encendida",
                ["Notifications"] = "Notificaciones",
                ["NewChapters"] = "Nuevos capítulos",
                ["NotifyNewChapters"] = "Notificar cuando haya nuevos capítulos",
                ["RecommendedNovels"] = "Novelas recomendadas",
                ["NotifyRecommended"] = "Recibir recomendaciones personalizadas",
                ["Downloads"] = "Descargas",
                ["WifiOnly"] = "Solo Wi-Fi",
                ["DownloadOnlyWifi"] = "Descargar solo con Wi-Fi",
                ["ChapterLimit"] = "Límite de capítulos",
                ["MaxChaptersPerNovel"] = "Máximo de capítulos por novela",
                ["Cache"] = "Caché",
                ["ClearCache"] = "Limpiar caché",
                ["CacheSize"] = "Tamaño del caché",

                //MorePage
                ["GuestUser"] = "Invitado",
                ["NoEmailRegistered"] = "No has iniciado sesión",
                ["GuestMode"] = "Modo invitado",
                ["MemberSince"] = "Miembro desde: {0}",
                ["IncognitoMode"] = "Modo incógnito",
                ["IncognitoModeDescription"] = "No se guardará el historial de lectura",
                ["FaceIdTouchId"] = "Face ID / Touch ID",
                ["NotConfigured"] = "No configurado",
                ["Activated"] = "Activado",
                ["DownloadQueue"] = "Cola de descargas",
                ["NoPendingDownloads"] = "Sin descargas pendientes",
                ["Categories"] = "Categorías",
                ["ManageOfflineNovels"] = "Gestiona tus novelas offline",
                ["About"] = "Acerca de",
                ["Administration"] = "Administración",
                ["CreateNovel"] = "Crear novela",
                ["ManageNovels"] = "Gestionar novelas",
                ["ManageGenres"] = "Gestionar géneros",
                ["TestConnection"] = "Probar conexión",
                ["ChangeProfilePhoto"] = "Cambiar foto de perfil",
                ["TakePhoto"] = "Tomar foto",
                ["ChooseFromGallery"] = "Elegir de galería",
                ["RemovePhoto"] = "Eliminar foto",
                ["PermissionRequired"] = "Se necesitan permisos para acceder a las fotos",
                ["CameraNotAvailable"] = "La cámara no está disponible en este dispositivo",
                ["GalleryNotAvailable"] = "La galería no está disponible en este dispositivo",
                ["PhotoUpdateSuccess"] = "Foto de perfil actualizada correctamente",
                ["PhotoRemoveSuccess"] = "Foto de perfil eliminada",
                ["ConfirmRemovePhoto"] = "¿Estás seguro de que deseas eliminar tu foto de perfil?",
                ["IncognitoActivated"] = "Modo incógnito activado. No se guardará el historial de lectura.",
                ["IncognitoDeactivated"] = "Modo incógnito desactivado.",
                ["RemovePhotoTitle"] = "Eliminar foto",
                ["ErrorProcessingPhoto"] = "Error al procesar la foto: {0}",
                ["ErrorRemovingPhoto"] = "Error al eliminar la foto: {0}",
                ["LoginRequiredProfilePhoto"] = "Debes iniciar sesión para cambiar tu foto de perfil",
                ["TakeProfilePhotoTitle"] = "Tomar foto de perfil",
                ["SelectProfilePhotoTitle"] = "Seleccionar foto de perfil",
                ["CameraPermissionRequired"] = "Se necesitan permisos de cámara para tomar fotos",
                ["PhotosPermissionRequired"] = "Se necesitan permisos para acceder a las fotos",
                ["CameraPermissionDenied"] = "No se otorgaron los permisos de cámara",
                ["PhotosPermissionDenied"] = "No se otorgaron los permisos de galería",
                ["ErrorTakingPhoto"] = "Error al tomar la foto: {0}",
                ["ErrorSelectingPhoto"] = "Error al seleccionar la foto: {0}",
                ["ProcessingPhoto"] = "Procesando foto...",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nTu biblioteca personal de novelas ligeras\n\nDesarrollado con ❤️ por tu equipo",
                ["Permissions"] = "Permisos",
                ["AddNovel"] = "Agregar nuevas novelas a la biblioteca",
                ["EditNovel"] = "Editar o eliminar novelas existentes",
                ["ManageDownload"] = "Maneja tus descargas",
                ["LogoutConfirmMessage"] = "¿Estás seguro de que deseas cerrar sesión?",

                // AppShell
                ["Library"] = "📚 Librería",
                ["Explore"] = "🌐 Explorar",
                ["History"] = "📝 Historial",
                ["More"] = "➕ Más",
                ["MyLibrary"] = "Mi Librería",
                ["ExploreNovels"] = "Explorar Novelas",
                ["ReadingHistory"] = "Historial de Lectura",
                ["MoreOptions"] = "Más Opciones",
                ["Settings"] = " Configuración",
                ["Downloads"] = "Descargas",
                ["Statistics"] = " Estadísticas",
                ["Logout"] = "🔐 Cerrar Sesión",
                ["YourPersonalLibrary"] = "Tu biblioteca personal",



                // Common
                ["OK"] = "OK",
                ["Cancel"] = "Cancelar",
                ["Yes"] = "Sí",
                ["No"] = "No",
                ["Save"] = "Guardar",
                ["Delete"] = "Eliminar",
                ["Edit"] = "Editar",
                ["Close"] = "Cerrar",
                ["Loading"] = "Cargando...",
                ["Error"] = "Error",
                ["Success"] = "Éxito",
                ["Warning"] = "Advertencia",
                ["Info"] = "Información",
                ["BiometricStatusEnabled"] = "Habilitada",
                ["BiometricStatusDisabled"] = "Deshabilitada",
                ["BiometricNotAvailable"] = "No disponible en este dispositivo",
                ["BiometricNotConfigured"] = "No configurado",
                ["LoginRequiredForFeature"] = "Inicia sesión para usar esta función",
                ["PasswordDialogTitle"] = "Confirma tu contraseña",
                ["PasswordDialogMessage"] = "Ingresa tu contraseña para continuar",
                ["IncorrectPassword"] = "Contraseña incorrecta",
                ["BiometricEnabled"] = "Face ID/Touch ID habilitado correctamente",
                ["BiometricDisabled"] = "Face ID/Touch ID desactivado",
                ["BiometricEnableTitle"] = "Habilitar Biometría",
                ["BiometricEnableMessage"] = "Usa tu huella digital o Face ID para confirmar",
                ["BiometricDisableTitle"] = "Desactivar Biometría",
                ["BiometricDisableMessage"] = "¿Estás seguro de que deseas desactivar Face ID/Touch ID?\n\nTendrás que ingresar tu contraseña manualmente la próxima vez.",
                ["BiometricDisableConfirm"] = "Sí, desactivar",
                ["BiometricConfirmDisable"] = "Confirmar Desactivación",
                ["BiometricCanceled"] = "No se pudo habilitar la autenticación biométrica",
                ["ClearCacheConfirm"] = "¿Estás seguro de que deseas limpiar el caché?",
                ["ClearCacheSuccess"] = "Caché limpiado correctamente",
                ["YesClear"] = "Sí, limpiar",
                ["LanguageChangeMessage"] = "El cambio de idioma se aplicará completamente al reiniciar la aplicación",
                ["AccountDetails"] = "Nombre: {0}\nEmail: {1}\nMiembro desde: {2}",
                ["ErrorChangingBiometric"] = "Error al cambiar configuración: {0}",
                ["ErrorEnablingBiometric"] = "Error al habilitar biometría: {0}",
                ["ErrorDisablingBiometric"] = "Error al desactivar biometría: {0}",
                ["ErrorClearingCache"] = "Error al limpiar caché: {0}",
                ["FillAllFields"] = "Por favor completa todos los campos",
                ["WelcomeBack"] = "Bienvenido {0}",
                ["ConnectionError"] = "Error de conexión. Verifica tu conexión a internet.",
                ["ForgotPasswordMessage"] = "Función próximamente disponible",
                ["ComingSoon"] = "Próximamente",
                ["WelcomeGuest"] = "¡Bienvenido Invitado!",
                ["BiometricLoginMessage"] = "Usa tu huella digital o Face ID para acceder a NovelBook",
                ["InvalidCredentials"] = "Las credenciales guardadas ya no son válidas",
                ["BiometricError"] = "Error en autenticación biométrica",
                ["EnableBiometricMessage"] = "¿Deseas habilitar el inicio de sesión con Face ID/Touch ID para futuros accesos?",
                ["BiometricSetupMessage"] = "Usa tu huella digital o Face ID para habilitar el acceso rápido",
                ["All"] = "Todas",
                ["BiometricCredentialsError"] = "No se pudieron recuperar las credenciales guardadas",
                ["TooManyAttempts"] = "Demasiados intentos fallidos. Usa tu contraseña.",
                ["Read"] = "leído",
                ["SortBy"] = "Ordenar por",
                ["RecentlyAdded"] = "Añadido recientemente",
                ["TitleAZ"] = "Título (A-Z)",
                ["TitleZA"] = "Título (Z-A)",
                ["LastRead"] = "Último leído",
                ["MoreChapters"] = "Más capítulos",
                ["LessChapters"] = "Menos capítulos",
                ["LoginToSeeLibrary"] = "Inicia sesión para ver tu biblioteca",
                ["LibraryEmpty"] = "Tu biblioteca está vacía",
                ["ErrorLoadingLibrary"] = "Error al cargar la biblioteca",
                ["NoNovelsInFilter"] = "No hay novelas en: {0}",
                ["Paused"] = "En pausa",
                ["PlanToRead"] = "Planeo leer",
                ["Sort"] = "Ordenar",
                ["Explore"] = "Explorar",
                ["By"] = "Por",
                ["FilterBy"] = "Filtrar por",
                ["BestRating"] = "Mejor calificación",
                ["MostRecent"] = "Más recientes",
                ["MostChapters"] = "Más capítulos",
                ["StatusOngoing"] = "Estado: En curso",
                ["StatusCompleted"] = "Estado: Completadas",
                ["ViewMore"] = "Ver más",
                ["ErrorLoadingNovels"] = "Error al cargar novelas",
                ["Ongoing"] = "En curso",
                ["Hiatus"] = "Pausada",
                ["AllGenres"] = "Todas",
                ["NovelDetails"] = "Detalles de Novela",
                ["StartReading"] = "Empezar a leer",
                ["Genres"] = "Géneros",
                ["UnreadChapters"] = "Sin leer",
                ["ReadChapters"] = "Leídos",
                ["LastUpdate"] = "Última actualización",
                ["Reader"] = "Lector",
                ["Previous"] = "← Anterior",
                ["Next"] = "Siguiente →",
                ["ReadingSettings"] = "Configuración de Lectura",
                ["Size"] = "Tamaño",
                ["LineSpacing"] = "Espaciado",
                ["BackgroundTheme"] = "Tema de fondo",
                ["TextAlignment"] = "Alineación",
                ["Font"] = "Fuente",
                ["Original"] = "Original",
                ["Close"] = "Cerrar",
                ["EndOfChapter"] = "Has llegado al último capítulo disponible",
                ["End"] = "Fin",
                ["LoadingChapter"] = "Cargando capítulo...",
                ["ErrorLoadingChapter"] = "No se pudo cargar el capítulo",
                ["BackToLibrary"] = "Volver a la biblioteca",
                ["More"] = "Más",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nTu biblioteca personal de novelas ligeras\n\nDesarrollado con ❤️ por tu equipo",
                ["Confirm"] = "Confirmar"
            },

            // English
            ["en"] = new Dictionary<string, string>
            {
                // LoginPage
                ["Welcome"] = "Welcome to NovelBook",
                ["WelcomeSubtitle"] = "Your light novel library",
                ["Email"] = "Email",
                ["Password"] = "Password",
                ["Login"] = "Login",
                ["Register"] = "Register",
                ["Guest"] = "Guest",
                ["ForgotPassword"] = "Forgot password?",
                ["LoginWithSocial"] = "Login with:",
                ["NoAccount"] = "Don't have an account?",
                ["LoggingIn"] = "Logging in...",
                ["BiometricLoginButton"] = "🔐 Login with Face ID/Touch ID",

                // RegisterPage
                ["RegisterTitle"] = "Register",
                ["YourLightNovelWorld"] = "Your light novel world",
                ["FillAllFieldsLabel"] = "Fill all fields:",
                ["Name"] = "Name",
                ["ConfirmPassword"] = "Confirm password",
                ["PasswordsDoNotMatch"] = "Passwords do not match",
                ["PasswordRequirement"] = "Password must be at least 6 characters",
                ["CreateAccount"] = "Create",
                ["CreatingAccount"] = "Creating account...",
                ["AlreadyHaveAccount"] = "Already have an account?",
                ["LoginHere"] = "Login",
                ["FillAllFieldsError"] = "Please fill all fields",
                ["InvalidEmailError"] = "Please enter a valid email",
                ["PasswordTooShortError"] = "Password must be at least 6 characters",
                ["PasswordsDontMatchError"] = "Passwords do not match",
                ["Success"] = "Success",
                ["AccountCreatedSuccess"] = "Account created successfully",
                ["ConnectionError"] = "Connection error. Check your internet connection.",

                // LibraryPage
                ["MyLibrary"] = "My Library",
                ["Reading"] = "Reading",
                ["Completed"] = "Completed",
                ["Favorites"] = "Favorites",
                ["NoNovels"] = "No novels in your library",
                ["SearchLibrary"] = "Search library...",
                ["Read"] = " read",
                ["Caps"] = " chaps",
                ["All"] = "All",
                ["Dropped"] = "Paused",
                ["PlanToRead"] = "Plan to Read",
                ["LoginToSeeLibrary"] = "Login to see your library",
                ["OptionsFor"] = "Options for:",
                ["Cancel"] = "Cancel",
                ["RemoveFromFavorites"] = "Remove from favorites",
                ["AddToFavorites"] = "Add to favorites",
                ["ChangeStatus"] = "Change status",
                ["StatusUpdated"] = "Status updated",
                ["ErrorPerformingAction"] = "Could not perform action",
                ["NewStatus"] = "New status",
                ["ChangeStatusTo"] = "Change reading status",
                ["ConfirmAction"] = "Are you sure?",
                ["MarkedAsFavorite"] = "Marked as favorite",
                ["RemovedFromFavorites"] = "Removed from favorites",

                // ExplorePage
                ["ExploreNovels"] = "Explore Novels",
                ["PopularGenres"] = "Popular Genres",
                ["AllNovels"] = "All Novels",
                ["FilterByGenre"] = "Filter by genre",
                ["FilterByStatus"] = "Filter by status",
                ["InProgress"] = "In progress",
                ["SearchNovels"] = "Search novels...",

                // HistoryPage
                ["History"] = "History",
                ["TotalTime"] = "Total time",
                ["ReadingStreak"] = "Streak",
                ["Days"] = "Days",
                ["CompleteHistory"] = "📅 Complete history",
                ["ByNovel"] = "📚 By novel",
                ["Today"] = "📆 Today",
                ["ThisWeek"] = "📅 This week",
                ["ThisMonth"] = "📅 This month",
                ["NoHistoryYet"] = "You haven't read any chapters yet",
                ["LoginToSeeHistory"] = "Login to see your reading history",
                ["ErrorLoadingHistory"] = "Error loading history: {0}",
                ["ConfirmClearHistory"] = "Are you sure you want to clear all your reading history?",
                ["HistoryCleared"] = "Your history has been cleared",
                ["ErrorClearingHistory"] = "Could not clear history",
                ["NoReadingToday"] = "You haven't read anything today",
                ["NoReadingThisWeek"] = "You haven't read anything this week",
                ["NoReadingThisMonth"] = "You haven't read anything this month",
                ["Completed2"] = "✓ Completed",
                ["Today"] = "📖 Today",
                ["Yesterday"] = "Yesterday",
                ["ChaptersRead"] = "📖 {0} chapters read",
                ["LastRead"] = "📅 Last read: {0}",

                // NovelDetailPage
                ["Read2"] = "Read",
                ["Reread"] = "Reread",
                ["Resume"] = "Resume",
                ["ResumeCap"] = "Resume Ch.",
                ["ContinueReading"] = "Continue reading",
                ["ContinueCap"] = "Continue Ch.",
                ["ReadCap"] = "Read Ch.",
                ["AddToLibrary"] = " Add",
                ["RemoveFromLibrary"] = " Remove",
                ["Synopsis"] = "Synopsis",
                ["Chapters"] = "Chapters",
                ["Details"] = "Details",
                ["Chapter"] = "Chapter",
                ["AllChapters"] = "All",
                ["Unread"] = "Unread",
                ["ReverseOrder"] = "↓↑",
                ["SearchChapter"] = "Search chapter...",
                ["NoChaptersYet"] = "This novel has no chapters yet",
                ["NoChaptersAvailable"] = "No chapters available",
                ["ChapterNotFound"] = "Chapter not found",
                ["Status"] = "Status:",
                ["Author"] = "Author:",
                ["LastUpdate"] = "Last update:",
                ["Views"] = "Views:",
                ["WithoutGenres"] = "No genres assigned",
                ["ConfirmRemoveFromLibrary"] = "Remove this novel from your library?",
                ["RemovedFromLibrary"] = "Novel removed from your library",
                ["AddedToLibrary"] = "Novel added to your library",
                ["ErrorAddingToLibrary"] = "Could not add to library",
                ["ErrorRemovingFromLibrary"] = "Could not remove from library",
                ["ErrorProcessingRequest"] = "Error processing request",
                ["ErrorLoadingDetails"] = "Error loading details",
                ["ViewReviews"] = "View reviews ({0})",

                // SettingsPage
                ["Settings"] = "Settings",
                ["Appearance"] = "Appearance",
                ["AppTheme"] = "App theme",
                ["System"] = "System",
                ["Light"] = "Light",
                ["Dark"] = "Dark",
                ["Language"] = "Language",
                ["Spanish"] = "Español",
                ["English"] = "English",
                ["Account"] = "Account",
                ["AccountInfo"] = "Account information",
                ["BiometricAuth"] = "Biometric authentication",
                ["ChangePassword"] = "Change password",
                ["Reading"] = "Reading",
                ["FontSize"] = "Font size",
                ["NightMode"] = "Automatic night mode",
                ["KeepScreenOn"] = "Keep screen on",
                ["Notifications"] = "Notifications",
                ["NewChapters"] = "New chapters",
                ["NotifyNewChapters"] = "Notify when new chapters available",
                ["RecommendedNovels"] = "Recommended novels",
                ["NotifyRecommended"] = "Receive personalized recommendations",
                ["Downloads"] = "Downloads",
                ["WifiOnly"] = "Wi-Fi only",
                ["DownloadOnlyWifi"] = "Download only on Wi-Fi",
                ["ChapterLimit"] = "Chapter limit",
                ["MaxChaptersPerNovel"] = "Maximum chapters per novel",
                ["Cache"] = "Cache",
                ["ClearCache"] = "Clear cache",
                ["CacheSize"] = "Cache size",



                // AppShell
                ["Library"] = "📚 Library",
                ["Explore"] = "🌐 Explore",
                ["History"] = "📝 History",
                ["More"] = "➕ More",
                ["MyLibrary"] = "My Library",
                ["ExploreNovels"] = "Explore Novels",
                ["ReadingHistory"] = "Reading History",
                ["MoreOptions"] = "More Options",
                ["Settings"] = " Settings",
                ["Downloads"] = "Downloads",
                ["Statistics"] = " Statistics",
                ["Logout"] = "🔐 Logout",
                ["YourPersonalLibrary"] = "Your personal library",

                // MorePage
                ["GuestUser"] = "Guest",
                ["NoEmailRegistered"] = "Not logged in",
                ["GuestMode"] = "Guest mode",
                ["MemberSince"] = "Member since: {0}",
                ["IncognitoMode"] = "Incognito mode",
                ["IncognitoModeDescription"] = "Reading history will not be saved",
                ["FaceIdTouchId"] = "Face ID / Touch ID",
                ["NotConfigured"] = "Not configured",
                ["Activated"] = "Activated",
                ["DownloadQueue"] = "Download queue",
                ["NoPendingDownloads"] = "No pending downloads",
                ["Categories"] = "Categories",
                ["ManageOfflineNovels"] = "Manage your offline novels",
                ["About"] = "About",
                ["Administration"] = "Administration",
                ["CreateNovel"] = "Create novel",
                ["ManageNovels"] = "Manage novels",
                ["ManageGenres"] = "Manage genres",
                ["TestConnection"] = "Test connection",
                ["ChangeProfilePhoto"] = "Change profile photo",
                ["TakePhoto"] = "Take photo",
                ["ChooseFromGallery"] = "Choose from gallery",
                ["RemovePhoto"] = "Remove photo",
                ["PermissionRequired"] = "Permission required to access photos",
                ["CameraNotAvailable"] = "Camera is not available on this device",
                ["GalleryNotAvailable"] = "Gallery is not available on this device",
                ["PhotoUpdateSuccess"] = "Profile photo updated successfully",
                ["PhotoRemoveSuccess"] = "Profile photo removed",
                ["ConfirmRemovePhoto"] = "Are you sure you want to remove your profile photo?",
                ["IncognitoActivated"] = "Incognito mode activated. Reading history will not be saved.",
                ["IncognitoDeactivated"] = "Incognito mode deactivated.",
                ["RemovePhotoTitle"] = "Remove photo",
                ["ErrorProcessingPhoto"] = "Error processing photo: {0}",
                ["ErrorRemovingPhoto"] = "Error removing photo: {0}",
                ["LoginRequiredProfilePhoto"] = "You must login to change your profile photo",
                ["TakeProfilePhotoTitle"] = "Take profile photo",
                ["SelectProfilePhotoTitle"] = "Select profile photo",
                ["CameraPermissionRequired"] = "Camera permission required to take photos",
                ["PhotosPermissionRequired"] = "Permission required to access photos",
                ["CameraPermissionDenied"] = "Camera permission was not granted",
                ["PhotosPermissionDenied"] = "Gallery permission was not granted",
                ["ErrorTakingPhoto"] = "Error taking photo: {0}",
                ["ErrorSelectingPhoto"] = "Error selecting photo: {0}",
                ["ProcessingPhoto"] = "Processing photo...",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nYour personal light novel library\n\nDeveloped with ❤️ by your team",
                ["Permissions"] = "Permissions",
                ["AddNovel"] = "Add new novels to the library",
                ["EditNovel"] = "Edit or delete existing novels",
                ["ManageDownload"] = "Manage your downloads",
                ["LogoutConfirmMessage"] = "Are you sure you want to logout?",

                // Common
                ["OK"] = "OK",
                ["Cancel"] = "Cancel",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["Save"] = "Save",
                ["Delete"] = "Delete",
                ["Edit"] = "Edit",
                ["Close"] = "Close",
                ["Loading"] = "Loading...",
                ["Error"] = "Error",
                ["Success"] = "Success",
                ["Warning"] = "Warning",
                ["Info"] = "Information",
                ["BiometricStatusEnabled"] = "Enabled",
                ["BiometricStatusDisabled"] = "Disabled",
                ["BiometricNotAvailable"] = "Not available on this device",
                ["BiometricNotConfigured"] = "Not configured",
                ["LoginRequiredForFeature"] = "Login required to use this feature",
                ["PasswordDialogTitle"] = "Confirm your password",
                ["PasswordDialogMessage"] = "Enter your password to continue",
                ["IncorrectPassword"] = "Incorrect password",
                ["BiometricEnabled"] = "Face ID/Touch ID enabled successfully",
                ["BiometricDisabled"] = "Face ID/Touch ID disabled",
                ["BiometricEnableTitle"] = "Enable Biometrics",
                ["BiometricEnableMessage"] = "Use your fingerprint or Face ID to confirm",
                ["BiometricDisableTitle"] = "Disable Biometrics",
                ["BiometricDisableMessage"] = "Are you sure you want to disable Face ID/Touch ID?\n\nYou'll need to enter your password manually next time.",
                ["BiometricDisableConfirm"] = "Yes, disable",
                ["BiometricConfirmDisable"] = "Confirm Deactivation",
                ["BiometricCanceled"] = "Could not enable biometric authentication",
                ["ClearCacheConfirm"] = "Are you sure you want to clear the cache?",
                ["ClearCacheSuccess"] = "Cache cleared successfully",
                ["YesClear"] = "Yes, clear",
                ["LanguageChangeMessage"] = "The language change will be fully applied after restarting the app",
                ["AccountDetails"] = "Name: {0}\nEmail: {1}\nMember since: {2}",
                ["ErrorChangingBiometric"] = "Error changing configuration: {0}",
                ["ErrorEnablingBiometric"] = "Error enabling biometrics: {0}",
                ["ErrorDisablingBiometric"] = "Error disabling biometrics: {0}",
                ["ErrorClearingCache"] = "Error clearing cache: {0}",
                ["FillAllFields"] = "Please fill in all fields",
                ["WelcomeBack"] = "Welcome back {0}",
                ["ConnectionError"] = "Connection error. Please check your internet connection.",
                ["ForgotPasswordMessage"] = "Feature coming soon",
                ["ComingSoon"] = "Coming soon",
                ["WelcomeGuest"] = "Welcome Guest!",
                ["BiometricLoginMessage"] = "Use your fingerprint or Face ID to access NovelBook",
                ["InvalidCredentials"] = "Saved credentials are no longer valid",
                ["BiometricError"] = "Biometric authentication error",
                ["EnableBiometricMessage"] = "Would you like to enable Face ID/Touch ID login for future access?",
                ["BiometricSetupMessage"] = "Use your fingerprint or Face ID to enable quick access",
                ["All"] = "All",
                ["BiometricCredentialsError"] = "Could not retrieve saved credentials",
                ["TooManyAttempts"] = "Too many failed attempts. Please use your password.",
                ["Read"] = "read",
                ["SortBy"] = "Sort by",
                ["RecentlyAdded"] = "Recently added",
                ["TitleAZ"] = "Title (A-Z)",
                ["TitleZA"] = "Title (Z-A)",
                ["LastRead"] = "Last read",
                ["MoreChapters"] = "More chapters",
                ["LessChapters"] = "Less chapters",
                ["LoginToSeeLibrary"] = "Login to see your library",
                ["LibraryEmpty"] = "Your library is empty",
                ["ErrorLoadingLibrary"] = "Error loading library",
                ["NoNovelsInFilter"] = "No novels in: {0}",
                ["Paused"] = "Paused",
                ["PlanToRead"] = "Plan to read",
                ["Sort"] = "Sort",
                ["Explore"] = "Explore",
                ["By"] = "By",
                ["FilterBy"] = "Filter by",
                ["BestRating"] = "Best rating",
                ["MostRecent"] = "Most recent",
                ["MostChapters"] = "Most chapters",
                ["StatusOngoing"] = "Status: Ongoing",
                ["StatusCompleted"] = "Status: Completed",
                ["ViewMore"] = "View more",
                ["ErrorLoadingNovels"] = "Error loading novels",
                ["Ongoing"] = "Ongoing",
                ["Hiatus"] = "On hiatus",
                ["AllGenres"] = "All",
                ["NovelDetails"] = "Novel Details",
                ["StartReading"] = "Start reading",
                ["Genres"] = "Genres",
                ["UnreadChapters"] = "Unread",
                ["ReadChapters"] = "Read",
                ["Reader"] = "Reader",
                ["Previous"] = "← Previous",
                ["Next"] = "Next →",
                ["ReadingSettings"] = "Reading Settings",
                ["Size"] = "Size",
                ["LineSpacing"] = "Line spacing",
                ["BackgroundTheme"] = "Background theme",
                ["TextAlignment"] = "Text alignment",
                ["Font"] = "Font",
                ["Original"] = "Original",
                ["Close"] = "Close",
                ["EndOfChapter"] = "You've reached the last available chapter",
                ["End"] = "End",
                ["LoadingChapter"] = "Loading chapter...",
                ["ErrorLoadingChapter"] = "Could not load chapter",
                ["BackToLibrary"] = "Back to library",
                ["More"] = "More",
                ["ChooseFromGallery"] = "Choose from gallery",
                ["RemovePhoto"] = "Remove photo",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nYour personal light novel library\n\nDeveloped with ❤️ by your team",
                ["Confirm"] = "Confirm"
            }
        };

        /// <summary>
        /// Obtiene el idioma actual de la aplicación
        /// </summary>
        public static string CurrentLanguage
        {
            get
            {
                var savedLanguage = Preferences.Get("AppLanguage", "system");
                if (savedLanguage == "system")
                {
                    // Obtener el idioma del sistema
                    var culture = CultureInfo.CurrentUICulture;
                    var languageCode = culture.TwoLetterISOLanguageName.ToLower();
                    return (languageCode == "es" || languageCode == "en") ? languageCode : "es";
                }
                return savedLanguage;
            }
        }

        /// <summary>
        /// Obtiene una traducción para la clave especificada
        /// </summary>
        public static string GetString(string key)
        {
            var language = CurrentLanguage;

            if (Translations.ContainsKey(language) && Translations[language].ContainsKey(key))
            {
                return Translations[language][key];
            }

            // Si no se encuentra la traducción, devolver la clave como fallback
            return key;
        }

        /// <summary>
        /// Obtiene una traducción con formato
        /// </summary>
        public static string GetString(string key, params object[] args)
        {
            var translation = GetString(key);
            return string.Format(translation, args);
        }

        /// <summary>
        /// Cambia el idioma de la aplicación
        /// </summary>
        public static void SetLanguage(string languageCode)
        {
            // Solo aceptar códigos de idioma válidos, no "system"
            if (languageCode != "es" && languageCode != "en")
            {
                return;
            }

            var culture = new CultureInfo(languageCode);
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
        }
    }
}