using System.Globalization;

namespace NovelBook.Services
{
    /// <summary>
    /// Servicio para manejar la localización y traducciones de la aplicación
    /// </summary>
    public static class LocalizationService
    {
        // Diccionario de traducciones
        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
        {
            // Español
            ["es"] = new Dictionary<string, string>
            {
                // LoginPage
                ["Welcome"] = "Bienvenido a NovelBook",
                ["WelcomeSubtitle"] = "Tu biblioteca de novelas ligeras",
                ["Email"] = "Correo electrónico",
                ["Password"] = "Contraseña",
                ["Login"] = "Entrar",
                ["Register"] = "Regístrate",
                ["Guest"] = "Invitado",
                ["ForgotPassword"] = "¿Olvidaste tu contraseña?",
                ["LoginWithSocial"] = "Iniciar sesión con:",
                ["NoAccount"] = "¿No tienes cuenta?",

                // LibraryPage
                ["MyLibrary"] = "Mi Biblioteca",
                ["Reading"] = "Leyendo",
                ["Completed"] = "Completadas",
                ["Favorites"] = "Favoritas",
                ["NoNovels"] = "No hay novelas en tu biblioteca",
                ["SearchLibrary"] = "Buscar en biblioteca...",

                // ExplorePage
                ["ExploreNovels"] = "Explorar Novelas",
                ["PopularGenres"] = "Géneros Populares",
                ["AllNovels"] = "Todas las Novelas",
                ["FilterByGenre"] = "Filtrar por género",
                ["FilterByStatus"] = "Filtrar por estado",
                ["InProgress"] = "En progreso",
                ["SearchNovels"] = "Buscar novelas...",

                // SettingsPage
                ["Settings"] = "Configuración",
                ["Appearance"] = "Apariencia",
                ["AppTheme"] = "Tema de la aplicación",
                ["System"] = "Sistema",
                ["Light"] = "Claro",
                ["Dark"] = "Oscuro",
                ["Language"] = "Idioma",
                ["Spanish"] = "Español",
                ["English"] = "English",
                ["Account"] = "Cuenta",
                ["AccountInfo"] = "Información de cuenta",
                ["Logout"] = "Cerrar sesión",
                ["BiometricAuth"] = "Autenticación biométrica",
                ["ChangePassword"] = "Cambiar contraseña",
                ["Reading"] = "Lectura",
                ["FontSize"] = "Tamaño de letra",
                ["NightMode"] = "Modo nocturno automático",
                ["KeepScreenOn"] = "Mantener pantalla encendida",
                ["Notifications"] = "Notificaciones",
                ["NewChapters"] = "Nuevos capítulos",
                ["NotifyNewChapters"] = "Notificar cuando haya nuevos capítulos",
                ["RecommendedNovels"] = "Novelas recomendadas",
                ["NotifyRecommended"] = "Recibir recomendaciones personalizadas",
                ["Downloads"] = "Descargas",
                ["WifiOnly"] = "Solo Wi-Fi",
                ["DownloadOnlyWifi"] = "Descargar solo con Wi-Fi",
                ["ChapterLimit"] = "Límite de capítulos",
                ["MaxChaptersPerNovel"] = "Máximo de capítulos por novela",
                ["Cache"] = "Caché",
                ["ClearCache"] = "Limpiar caché",
                ["CacheSize"] = "Tamaño del caché",

                // Common
                ["OK"] = "OK",
                ["Cancel"] = "Cancelar",
                ["Yes"] = "Sí",
                ["No"] = "No",
                ["Save"] = "Guardar",
                ["Delete"] = "Eliminar",
                ["Edit"] = "Editar",
                ["Close"] = "Cerrar",
                ["Loading"] = "Cargando...",
                ["Error"] = "Error",
                ["Success"] = "Éxito",
                ["Warning"] = "Advertencia",
                ["Info"] = "Información",
                ["GuestMode"] = "Modo invitado",
                ["LogoutConfirmMessage"] = "¿Estás seguro de que deseas cerrar sesión?",
                ["BiometricStatusEnabled"] = "Habilitada",
                ["BiometricStatusDisabled"] = "Deshabilitada",
                ["BiometricNotAvailable"] = "No disponible en este dispositivo",
                ["BiometricNotConfigured"] = "No configurado",
                ["LoginRequiredForFeature"] = "Inicia sesión para usar esta función",
                ["PasswordDialogTitle"] = "Confirma tu contraseña",
                ["PasswordDialogMessage"] = "Ingresa tu contraseña para continuar",
                ["IncorrectPassword"] = "Contraseña incorrecta",
                ["BiometricEnabled"] = "Face ID/Touch ID habilitado correctamente",
                ["BiometricDisabled"] = "Face ID/Touch ID desactivado",
                ["BiometricEnableTitle"] = "Habilitar Biometría",
                ["BiometricEnableMessage"] = "Usa tu huella digital o Face ID para confirmar",
                ["BiometricDisableTitle"] = "Desactivar Biometría",
                ["BiometricDisableMessage"] = "¿Estás seguro de que deseas desactivar Face ID/Touch ID?\n\nTendrás que ingresar tu contraseña manualmente la próxima vez.",
                ["BiometricDisableConfirm"] = "Sí, desactivar",
                ["BiometricConfirmDisable"] = "Confirmar Desactivación",
                ["BiometricCanceled"] = "No se pudo habilitar la autenticación biométrica",
                ["ClearCacheConfirm"] = "¿Estás seguro de que deseas limpiar el caché?",
                ["ClearCacheSuccess"] = "Caché limpiado correctamente",
                ["YesClear"] = "Sí, limpiar",
                ["LanguageChangeMessage"] = "El cambio de idioma se aplicará completamente al reiniciar la aplicación",
                ["AccountDetails"] = "Nombre: {0}\nEmail: {1}\nMiembro desde: {2}",
                ["MemberSince"] = "Miembro desde",
                ["ErrorChangingBiometric"] = "Error al cambiar configuración: {0}",
                ["ErrorEnablingBiometric"] = "Error al habilitar biometría: {0}",
                ["ErrorDisablingBiometric"] = "Error al desactivar biometría: {0}",
                ["ErrorClearingCache"] = "Error al limpiar caché: {0}",
                ["FillAllFields"] = "Por favor completa todos los campos",
                ["WelcomeBack"] = "Bienvenido {0}",
                ["ConnectionError"] = "Error de conexión. Verifica tu conexión a internet.",
                ["ForgotPasswordMessage"] = "Función próximamente disponible",
                ["ComingSoon"] = "Próximamente",
                ["WelcomeGuest"] = "¡Bienvenido Invitado!",
                ["BiometricLoginMessage"] = "Usa tu huella digital o Face ID para acceder a NovelBook",
                ["InvalidCredentials"] = "Las credenciales guardadas ya no son válidas",
                ["BiometricError"] = "Error en autenticación biométrica",
                ["EnableBiometricMessage"] = "¿Deseas habilitar el inicio de sesión con Face ID/Touch ID para futuros accesos?",
                ["BiometricSetupMessage"] = "Usa tu huella digital o Face ID para habilitar el acceso rápido",
                ["All"] = "Todas",
                ["BiometricCredentialsError"] = "No se pudieron recuperar las credenciales guardadas",
                ["TooManyAttempts"] = "Demasiados intentos fallidos. Usa tu contraseña.",
                ["Read"] = "leído",
                ["SortBy"] = "Ordenar por",
                ["RecentlyAdded"] = "Añadido recientemente",
                ["TitleAZ"] = "Título (A-Z)",
                ["TitleZA"] = "Título (Z-A)",
                ["LastRead"] = "Último leído",
                ["MoreChapters"] = "Más capítulos",
                ["LessChapters"] = "Menos capítulos",
                ["LoginToSeeLibrary"] = "Inicia sesión para ver tu biblioteca",
                ["LibraryEmpty"] = "Tu biblioteca está vacía",
                ["ErrorLoadingLibrary"] = "Error al cargar la biblioteca",
                ["NoNovelsInFilter"] = "No hay novelas en: {0}",
                ["Paused"] = "En pausa",
                ["PlanToRead"] = "Planeo leer",
                ["Sort"] = "Ordenar",
                ["Explore"] = "Explorar",
                ["By"] = "Por",
                ["Chapters"] = "capítulos",
                ["FilterBy"] = "Filtrar por",
                ["BestRating"] = "Mejor calificación",
                ["MostRecent"] = "Más recientes",
                ["MostChapters"] = "Más capítulos",
                ["StatusOngoing"] = "Estado: En curso",
                ["StatusCompleted"] = "Estado: Completadas",
                ["ViewMore"] = "Ver más",
                ["ErrorLoadingNovels"] = "Error al cargar novelas",
                ["Ongoing"] = "En curso",
                ["Completed"] = "Completada",
                ["Hiatus"] = "Pausada",
                ["AllGenres"] = "Todas",
                ["NovelDetails"] = "Detalles de Novela",
                ["StartReading"] = "Empezar a leer",
                ["ContinueReading"] = "Continuar leyendo",
                ["AddToLibrary"] = "Agregar a biblioteca",
                ["RemoveFromLibrary"] = "Quitar de biblioteca",
                ["Synopsis"] = "Sinopsis",
                ["Details"] = "Detalles",
                ["Genres"] = "Géneros",
                ["SearchChapter"] = "Buscar capítulo...",
                ["AllChapters"] = "Todos",
                ["UnreadChapters"] = "Sin leer",
                ["ReadChapters"] = "Leídos",
                ["LastUpdate"] = "Última actualización",
                ["Views"] = "Vistas",
                ["ViewReviews"] = "Ver reseñas ({0})",
                ["NoChaptersYet"] = "Esta novela no tiene capítulos aún",
                ["NoChaptersAvailable"] = "No se encontraron capítulos disponibles",
                ["ChapterNotFound"] = "No se encontró el capítulo solicitado",
                ["ConfirmRemoveFromLibrary"] = "¿Eliminar esta novela de tu biblioteca?",
                ["RemovedFromLibrary"] = "Novela eliminada de tu biblioteca",
                ["AddedToLibrary"] = "Novela agregada a tu biblioteca",
                ["ErrorAddingToLibrary"] = "No se pudo agregar a la biblioteca",
                ["ErrorRemovingFromLibrary"] = "No se pudo eliminar de la biblioteca",
                ["ErrorProcessingRequest"] = "Error al procesar la solicitud",
                ["Chapter"] = "Capítulo",
                ["Reader"] = "Lector",
                ["Previous"] = "← Anterior",
                ["Next"] = "Siguiente →",
                ["ReadingSettings"] = "Configuración de Lectura",
                ["Size"] = "Tamaño",
                ["LineSpacing"] = "Espaciado",
                ["BackgroundTheme"] = "Tema de fondo",
                ["TextAlignment"] = "Alineación",
                ["Font"] = "Fuente",
                ["Original"] = "Original",
                ["Close"] = "Cerrar",
                ["EndOfChapter"] = "Has llegado al último capítulo disponible",
                ["End"] = "Fin",
                ["LoadingChapter"] = "Cargando capítulo...",
                ["ErrorLoadingChapter"] = "No se pudo cargar el capítulo",
                ["BackToLibrary"] = "Volver a la biblioteca",
                ["More"] = "Más",
                ["GuestUser"] = "Usuario Invitado",
                ["NoEmailRegistered"] = "Sin correo registrado",
                ["IncognitoMode"] = "Modo incógnito",
                ["IncognitoModeDescription"] = "No se guardará el historial de lectura",
                ["DownloadQueue"] = "Cola de descargas",
                ["Categories"] = "Categorías",
                ["Statistics"] = "Estadísticas",
                ["About"] = "Acerca de",
                ["CreateNovel"] = "Crear novela",
                ["ManageNovels"] = "Gestionar novelas",
                ["TakePhoto"] = "Tomar foto",
                ["ChooseFromGallery"] = "Elegir de galería",
                ["RemovePhoto"] = "Eliminar foto",
                ["ChangeProfilePhoto"] = "Cambiar foto de perfil",
                ["PermissionRequired"] = "Se necesitan permisos para acceder a las fotos",
                ["CameraNotAvailable"] = "La cámara no está disponible en este dispositivo",
                ["GalleryNotAvailable"] = "La galería no está disponible en este dispositivo",
                ["PhotoUpdateSuccess"] = "Foto de perfil actualizada correctamente",
                ["PhotoRemoveSuccess"] = "Foto de perfil eliminada",
                ["ConfirmRemovePhoto"] = "¿Estás seguro de que deseas eliminar tu foto de perfil?",
                ["IncognitoActivated"] = "Modo incógnito activado. No se guardará el historial de lectura.",
                ["IncognitoDeactivated"] = "Modo incógnito desactivado.",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nTu biblioteca personal de novelas ligeras\n\nDesarrollado con ❤️ por tu equipo",
                ["Confirm"] = "Confirmar"
            },

            // English
            ["en"] = new Dictionary<string, string>
            {
                // LoginPage
                ["Welcome"] = "Welcome to NovelBook",
                ["WelcomeSubtitle"] = "Your light novel library",
                ["Email"] = "Email",
                ["Password"] = "Password",
                ["Login"] = "Login",
                ["Register"] = "Register",
                ["Guest"] = "Guest",
                ["ForgotPassword"] = "Forgot password?",
                ["LoginWithSocial"] = "Login with:",
                ["NoAccount"] = "Don't have an account?",

                // LibraryPage
                ["MyLibrary"] = "My Library",
                ["Reading"] = "Reading",
                ["Completed"] = "Completed",
                ["Favorites"] = "Favorites",
                ["NoNovels"] = "No novels in your library",
                ["SearchLibrary"] = "Search library...",

                // ExplorePage
                ["ExploreNovels"] = "Explore Novels",
                ["PopularGenres"] = "Popular Genres",
                ["AllNovels"] = "All Novels",
                ["FilterByGenre"] = "Filter by genre",
                ["FilterByStatus"] = "Filter by status",
                ["InProgress"] = "In progress",
                ["SearchNovels"] = "Search novels...",

                // SettingsPage
                ["Settings"] = "Settings",
                ["Appearance"] = "Appearance",
                ["AppTheme"] = "App theme",
                ["System"] = "System",
                ["Light"] = "Light",
                ["Dark"] = "Dark",
                ["Language"] = "Language",
                ["Spanish"] = "Español",
                ["English"] = "English",
                ["Account"] = "Account",
                ["AccountInfo"] = "Account information",
                ["Logout"] = "Logout",
                ["BiometricAuth"] = "Biometric authentication",
                ["ChangePassword"] = "Change password",
                ["Reading"] = "Reading",
                ["FontSize"] = "Font size",
                ["NightMode"] = "Automatic night mode",
                ["KeepScreenOn"] = "Keep screen on",
                ["Notifications"] = "Notifications",
                ["NewChapters"] = "New chapters",
                ["NotifyNewChapters"] = "Notify when new chapters available",
                ["RecommendedNovels"] = "Recommended novels",
                ["NotifyRecommended"] = "Receive personalized recommendations",
                ["Downloads"] = "Downloads",
                ["WifiOnly"] = "Wi-Fi only",
                ["DownloadOnlyWifi"] = "Download only on Wi-Fi",
                ["ChapterLimit"] = "Chapter limit",
                ["MaxChaptersPerNovel"] = "Maximum chapters per novel",
                ["Cache"] = "Cache",
                ["ClearCache"] = "Clear cache",
                ["CacheSize"] = "Cache size",

                // Common
                ["OK"] = "OK",
                ["Cancel"] = "Cancel",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["Save"] = "Save",
                ["Delete"] = "Delete",
                ["Edit"] = "Edit",
                ["Close"] = "Close",
                ["Loading"] = "Loading...",
                ["Error"] = "Error",
                ["Success"] = "Success",
                ["Warning"] = "Warning",
                ["Info"] = "Information",
                ["GuestMode"] = "Guest mode",
                ["LogoutConfirmMessage"] = "Are you sure you want to logout?",
                ["BiometricStatusEnabled"] = "Enabled",
                ["BiometricStatusDisabled"] = "Disabled",
                ["BiometricNotAvailable"] = "Not available on this device",
                ["BiometricNotConfigured"] = "Not configured",
                ["LoginRequiredForFeature"] = "Login required to use this feature",
                ["PasswordDialogTitle"] = "Confirm your password",
                ["PasswordDialogMessage"] = "Enter your password to continue",
                ["IncorrectPassword"] = "Incorrect password",
                ["BiometricEnabled"] = "Face ID/Touch ID enabled successfully",
                ["BiometricDisabled"] = "Face ID/Touch ID disabled",
                ["BiometricEnableTitle"] = "Enable Biometrics",
                ["BiometricEnableMessage"] = "Use your fingerprint or Face ID to confirm",
                ["BiometricDisableTitle"] = "Disable Biometrics",
                ["BiometricDisableMessage"] = "Are you sure you want to disable Face ID/Touch ID?\n\nYou'll need to enter your password manually next time.",
                ["BiometricDisableConfirm"] = "Yes, disable",
                ["BiometricConfirmDisable"] = "Confirm Deactivation",
                ["BiometricCanceled"] = "Could not enable biometric authentication",
                ["ClearCacheConfirm"] = "Are you sure you want to clear the cache?",
                ["ClearCacheSuccess"] = "Cache cleared successfully",
                ["YesClear"] = "Yes, clear",
                ["LanguageChangeMessage"] = "The language change will be fully applied after restarting the app",
                ["AccountDetails"] = "Name: {0}\nEmail: {1}\nMember since: {2}",
                ["MemberSince"] = "Member since",
                ["ErrorChangingBiometric"] = "Error changing configuration: {0}",
                ["ErrorEnablingBiometric"] = "Error enabling biometrics: {0}",
                ["ErrorDisablingBiometric"] = "Error disabling biometrics: {0}",
                ["ErrorClearingCache"] = "Error clearing cache: {0}",
                ["FillAllFields"] = "Please fill in all fields",
                ["WelcomeBack"] = "Welcome back {0}",
                ["ConnectionError"] = "Connection error. Please check your internet connection.",
                ["ForgotPasswordMessage"] = "Feature coming soon",
                ["ComingSoon"] = "Coming soon",
                ["WelcomeGuest"] = "Welcome Guest!",
                ["BiometricLoginMessage"] = "Use your fingerprint or Face ID to access NovelBook",
                ["InvalidCredentials"] = "Saved credentials are no longer valid",
                ["BiometricError"] = "Biometric authentication error",
                ["EnableBiometricMessage"] = "Would you like to enable Face ID/Touch ID login for future access?",
                ["BiometricSetupMessage"] = "Use your fingerprint or Face ID to enable quick access",
                ["All"] = "All",
                ["BiometricCredentialsError"] = "Could not retrieve saved credentials",
                ["TooManyAttempts"] = "Too many failed attempts. Please use your password.",
                ["Read"] = "read",
                ["SortBy"] = "Sort by",
                ["RecentlyAdded"] = "Recently added",
                ["TitleAZ"] = "Title (A-Z)",
                ["TitleZA"] = "Title (Z-A)",
                ["LastRead"] = "Last read",
                ["MoreChapters"] = "More chapters",
                ["LessChapters"] = "Less chapters",
                ["LoginToSeeLibrary"] = "Login to see your library",
                ["LibraryEmpty"] = "Your library is empty",
                ["ErrorLoadingLibrary"] = "Error loading library",
                ["NoNovelsInFilter"] = "No novels in: {0}",
                ["Paused"] = "Paused",
                ["PlanToRead"] = "Plan to read",
                ["Sort"] = "Sort",
                ["Explore"] = "Explore",
                ["By"] = "By",
                ["Chapters"] = "chapters",
                ["FilterBy"] = "Filter by",
                ["BestRating"] = "Best rating",
                ["MostRecent"] = "Most recent",
                ["MostChapters"] = "Most chapters",
                ["StatusOngoing"] = "Status: Ongoing",
                ["StatusCompleted"] = "Status: Completed",
                ["ViewMore"] = "View more",
                ["ErrorLoadingNovels"] = "Error loading novels",
                ["Ongoing"] = "Ongoing",
                ["Completed"] = "Completed",
                ["Hiatus"] = "On hiatus",
                ["AllGenres"] = "All",
                ["NovelDetails"] = "Novel Details",
                ["StartReading"] = "Start reading",
                ["ContinueReading"] = "Continue reading",
                ["AddToLibrary"] = "Add to library",
                ["RemoveFromLibrary"] = "Remove from library",
                ["Synopsis"] = "Synopsis",
                ["Details"] = "Details",
                ["Genres"] = "Genres",
                ["SearchChapter"] = "Search chapter...",
                ["AllChapters"] = "All",
                ["UnreadChapters"] = "Unread",
                ["ReadChapters"] = "Read",
                ["LastUpdate"] = "Last update",
                ["Views"] = "Views",
                ["ViewReviews"] = "View reviews ({0})",
                ["NoChaptersYet"] = "This novel has no chapters yet",
                ["NoChaptersAvailable"] = "No chapters available",
                ["ChapterNotFound"] = "Chapter not found",
                ["ConfirmRemoveFromLibrary"] = "Remove this novel from your library?",
                ["RemovedFromLibrary"] = "Novel removed from your library",
                ["AddedToLibrary"] = "Novel added to your library",
                ["ErrorAddingToLibrary"] = "Could not add to library",
                ["ErrorRemovingFromLibrary"] = "Could not remove from library",
                ["ErrorProcessingRequest"] = "Error processing request",
                ["Chapter"] = "Chapter",
                ["Reader"] = "Reader",
                ["Previous"] = "← Previous",
                ["Next"] = "Next →",
                ["ReadingSettings"] = "Reading Settings",
                ["Size"] = "Size",
                ["LineSpacing"] = "Line spacing",
                ["BackgroundTheme"] = "Background theme",
                ["TextAlignment"] = "Text alignment",
                ["Font"] = "Font",
                ["Original"] = "Original",
                ["Close"] = "Close",
                ["EndOfChapter"] = "You've reached the last available chapter",
                ["End"] = "End",
                ["LoadingChapter"] = "Loading chapter...",
                ["ErrorLoadingChapter"] = "Could not load chapter",
                ["BackToLibrary"] = "Back to library",
                ["More"] = "More",
                ["GuestUser"] = "Guest User",
                ["NoEmailRegistered"] = "No email registered",
                ["IncognitoMode"] = "Incognito mode",
                ["IncognitoModeDescription"] = "Reading history will not be saved",
                ["DownloadQueue"] = "Download queue",
                ["Categories"] = "Categories",
                ["Statistics"] = "Statistics",
                ["About"] = "About",
                ["CreateNovel"] = "Create novel",
                ["ManageNovels"] = "Manage novels",
                ["TakePhoto"] = "Take photo",
                ["ChooseFromGallery"] = "Choose from gallery",
                ["RemovePhoto"] = "Remove photo",
                ["ChangeProfilePhoto"] = "Change profile photo",
                ["PermissionRequired"] = "Permission required to access photos",
                ["CameraNotAvailable"] = "Camera is not available on this device",
                ["GalleryNotAvailable"] = "Gallery is not available on this device",
                ["PhotoUpdateSuccess"] = "Profile photo updated successfully",
                ["PhotoRemoveSuccess"] = "Profile photo removed",
                ["ConfirmRemovePhoto"] = "Are you sure you want to remove your profile photo?",
                ["IncognitoActivated"] = "Incognito mode activated. Reading history will not be saved.",
                ["IncognitoDeactivated"] = "Incognito mode deactivated.",
                ["AboutMessage"] = "NovelBook v1.0.0\n\nYour personal light novel library\n\nDeveloped with ❤️ by your team",
                ["Confirm"] = "Confirm"
            }
        };

        /// <summary>
        /// Obtiene el idioma actual de la aplicación
        /// </summary>
        public static string CurrentLanguage => Preferences.Get("AppLanguage", "es");

        /// <summary>
        /// Obtiene una traducción para la clave especificada
        /// </summary>
        public static string GetString(string key)
        {
            var language = CurrentLanguage;

            if (Translations.ContainsKey(language) && Translations[language].ContainsKey(key))
            {
                return Translations[language][key];
            }

            // Si no se encuentra la traducción, devolver la clave como fallback
            return key;
        }

        /// <summary>
        /// Obtiene una traducción con formato
        /// </summary>
        public static string GetString(string key, params object[] args)
        {
            var translation = GetString(key);
            return string.Format(translation, args);
        }

        /// <summary>
        /// Cambia el idioma de la aplicación
        /// </summary>
        public static void SetLanguage(string languageCode)
        {
            Preferences.Set("AppLanguage", languageCode);

            var culture = new CultureInfo(languageCode);
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
        }
    }
}